
version: 2

models:
  - name: social__fact_widget_deployments
    description: |-
      Cleaned and curated widget deployments on Near Social.

    columns:
      - name: ACTION_ID_SOCIAL
        description: "{{ doc('block_id')}}"

      - name: TX_HASH
        description: "{{ doc('tx_hash')}}"
        tests:
          - not_null:
              where: inserted_timestamp >= SYSDATE() - INTERVAL '{{ var('DBT_TEST_LOOKBACK_DAYS', 14) }} days'

      - name: BLOCK_ID
        description: "{{ doc('block_id')}}"

      - name: BLOCK_TIMESTAMP
        description: "{{ doc('block_timestamp')}}"
        tests:
          - not_null:
              where: inserted_timestamp >= SYSDATE() - INTERVAL '{{ var('DBT_TEST_LOOKBACK_DAYS', 14) }} days'

      - name: SIGNER_ID
        description: "{{ doc('signer_id')}}"

      - name: WIDGET_NAME
        description: "{{ doc('widget_name')}}"

      - name: SOURCE_CODE
        description: "{{ doc('source_code')}}"

      - name: METADATA
        description: "{{ doc('metadata')}}"

      - name: BRANCH
        description: "{{ doc('branch')}}"

      - name: WIDGET_MODULES_USED
        description: "{{ doc('widget_modules_used')}}"

      - name: WIDGET_URL
        description: "{{ doc('widget_url')}}"

      - name: FACT_WIDGET_DEPLOYMENTS_ID
        description: "{{doc('id')}}"
        tests:
          - unique:
              where: inserted_timestamp >= SYSDATE() - INTERVAL '{{ var('DBT_TEST_LOOKBACK_DAYS', 14) }} days'
          - not_null:
              where: inserted_timestamp >= SYSDATE() - INTERVAL '{{ var('DBT_TEST_LOOKBACK_DAYS', 14) }} days'

      - name: INSERTED_TIMESTAMP
        description: "{{doc('inserted_timestamp')}}"

      - name: MODIFIED_TIMESTAMP
        description: "{{doc('modified_timestamp')}}"
