near:
  config:
    send_anonymous_usage_stats: false
  outputs:
    dev:
      account: vna27887.us-east-1
      client_session_keep_alive: false
      database: NEAR_DEV
      authenticator: externalbrowser
      region: us-east-1
      role: INTERNAL_DEV
      schema: SILVER
      threads: 4
      type: snowflake
      user: juan@flipsidecrypto.com
      warehouse: DATA_SCIENCE
  target: dev
