version: 2

models:
  - name: metric_miner_count
    description: "The distinct number of miners within a given period"
    columns:
      - name: metric_date
        description: The date the metric occurred
        tests:
          - not_null
      - name: metric_period
        description: i.e. Hourly, Daily, etc.
        tests:
          - not_null
      - name: miner_count
        description: The distinct count of miners active in that period.
        tests:
          - not_null