name: dbt_run_streamline_chunks_realtime
run-name: dbt_run_streamline_chunks_realtime

on:
  workflow_dispatch:
  schedule:
    # Runs on 10 and 40 minutes (see https://crontab.guru)
    - cron: "10,40 * * * *"

env:
  USE_VARS: "${{ vars.USE_VARS }}"
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  dbt:
    runs-on: ubuntu-latest
    environment:
      name: workflow_prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Run DBT Jobs
        run: |
          dbt run -s 2+streamline__chunks_realtime --vars '{"STREAMLINE_INVOKE_STREAMS": True}'

      - name: Store logs
        uses: actions/upload-artifact@v4
        with:
          name: dbt-logs
          path: |
            logs
            target

notify-failure:
  needs: [dbt]
  if: failure()
  uses: ./.github/workflows/slack_notify.yml
  secrets:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
