version: 2

sources:
  - name: gold
    schema: gold
    database: flipside_prod_db
    tables:
      - name: near_address_labels

  - name: streamline_dev
    database: streamline
    schema: near_dev
    tables:
      - name: blocks
      - name: shards

  - name: crosschain
    schema: core
    database: crosschain
    tables:
      - name: address_labels
      - name: dim_dates

  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: number_sequence
