version: 2

sources:
  - name: crosschain
    schema: core
    database: crosschain
    tables:
      - name: dim_dates

  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: number_sequence
      - name: github_activity
      - name: labels_combined

  - name: streamline
    database: streamline
    schema: near_lake
    tables:
      - name: blocks
      - name: shards
