version: 2

sources:
  - name: streamline_dev
    database: streamline
    schema: near_dev
    tables:
      - name: blocks
      - name: shards

  - name: crosschain
    schema: core
    database: crosschain
    tables:
      - name: dim_labels
      - name: dim_dates

  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: number_sequence
      - name: github_activity
