version: 2

sources:
  - name: crosschain
    schema: core
    database: crosschain
    tables:
      - name: dim_dates

  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: number_sequence
      - name: github_activity
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices

  - name: streamline
    database: streamline
    schema: near_lake
    tables:
      - name: blocks
      - name: shards
